---
- name: Prepare Ceph RBD Pools with Cluster Mode
  shell: |
    incus storage create {{ item.name }} ceph --target={{ inventory_hostname }}
  register: prepare_cluster_ceph_rbd_pools
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ pools.ceph.rbd }}"
- debug: msg={{ prepare_cluster_ceph_rbd_pools }}


- name: Create Ceph RBD Pools
  shell: |
    incus storage create {{ item.name }} ceph
  register: create_ceph_rbd_pools
  with_items:
    - "{{ pools.ceph.rbd }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_ceph_rbd_pools }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Prepare Ceph Filesystem Pools with Cluster Mode
  shell: |
    incus storage create {{ item.name }} cephfs source={{ item.source }} --target={{ inventory_hostname }}
  register: prepare_cluster_ceph_fs_pools
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ pools.ceph.fs }}"
- debug: msg={{ prepare_cluster_ceph_fs_pools }}


- name: Create Ceph Filesystem Pools
  shell: |
    incus storage create {{ item.name }} cephfs
  register: create_ceph_fs_pools
  with_items:
    - "{{ pools.ceph.fs }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_ceph_fs_pools }}
  when: print_debug == true and inventory_hostname in groups['control']

