---
- name: Install CephFS Client Packages
  package: name={{ item }} state=present
  register: install_ceph_clients
  until: install_ceph_clients is succeeded
  retries: 5
  delay: 10
  with_items:
    - "ceph-common"
- debug: msg={{ install_ceph_clients }}
  when: print_debug == true


- name: Copy Ceph Configuration for CephFS Clients
  synchronize:
    mode: push
    src:  "/etc/ceph/"
    dest: "/etc/ceph/"
    set_remote_user: true
    rsync_opts:
      - "-e ssh"          # "-e ssh -i ~/.ssh/id_rsa.pub"
    ssh_args:
      - "-p {{ _incus.ceph.passwd }} -o StrictHostKeyChecking=no"
  delegate_to: "{{ _incus.ceph.control_ip_addr }}"
  delegate_facts: true
  register: copy_ceph_config
- debug: msg={{ copy_ceph_config }}
  when: print_debug == true


#- name: Copy Ceph Configuration with Rsync for CephFS Clients
#  become_user: root
#  shell: |
#    rsync -a --rsh='/usr/bin/sshpass -p {{ _incus.ceph.passwd }} ssh -o StrictHostKeyChecking=no' /etc/ceph/ {{ inventory_hostname }}:/etc/ceph/
#  delegate_to: "{{ _incus.ceph.control_ip_addr }}"

