# You can export the full content of your custom storage volume to a standalone file that can be stored at any location. For highest reliability, store the backup file on a different file system to ensure that it does not get lost or corrupted.
#
# Export a custom storage volume
# Use the following command to export a custom storage volume to a compressed file (for example, /path/to/my-backup.tgz):
# $ incus storage volume export <pool_name> <volume_name> [<file_path>]
#
# If you do not specify a file path, the export file is saved as backup.tar.gz in the working directory.
# Warning
# If the output file already exists, the command overwrites the existing file without warning.
#
# You can add any of the following flags to the command:
#
# --compression
# By default, the output file uses gzip compression. You can specify a different compression algorithm (for example, bzip2)
# or turn off compression with --compression=none.
#
# --optimized-storage
# If your storage pool uses the btrfs or the zfs driver, add the --optimized-storage flag to store the data
# as a driver-specific binary blob instead of an archive of individual files. In this case, the export file can only be used with pools that use the same storage driver.
#
# Exporting a volume in optimized mode is usually quicker than exporting the individual files.
# Snapshots are exported as differences from the main volume, which decreases their size and makes them easily accessible.
#
# --volume-only
# By default, the export file contains all snapshots of the storage volume. Add this flag to export the volume without its snapshots.
#
# Restore a custom storage volume from an export file
# You can import an export file (for example, /path/to/my-backup.tgz) as a new custom storage volume. To do so, use the following command:
# $ incus storage volume import <pool_name> <file_path> [<volume_name>]
#
# If you do not specify a volume name, the original name of the exported storage volume is used for the new volume.
# If a volume with that name already (or still) exists in the specified storage pool, the command returns an error.
# In that case, either delete the existing volume before importing the backup or specify a different volume name for the import.

