---
- name: Delete LVM VGs Volumes
  shell: |
    incus storage volume delete {{ item.pool }} {{ item.name }}
  register: delete_volumes
  ignore_errors: true
  with_items:
    - "{{ volumes.lvm.vgs }}"
- debug: msg={{ delete_volumes }}

