---
#- name: Delete Partition
#  parted:
#    device: "{{ item.source }}"
#    number: "1"
#    state: absent
#  register: delete_partition
#  ignore_errors: true
#  with_items:
#    - "{{ pools.btrfs.block }}"
#- debug: msg={{ delete_partition }}


#- name: Destroy ZFS ZPool
#  shell: |
#    zpool destroy {{ item.zpool }}
#  register: destroy_zfs_zpool
#  ignore_errors: true
#  with_items:
#    - "{{ pools.zfs.zpool }}"
#- debug: msg={{ destroy_zfs_zpool }}
# dd if=/dev/zero of="{{ item.source }}1" seek=$(( $(blockdev --getsz "{{ item.source }}1") - ( ( 256 * 1024 * 2) / $(blockdev --getpbsz "{{ item.source}}1") ) ))


- name: Clean ZPool Devices
  shell: |
    for dn in `echo "{{ item.source }}"`
    do
      dd if=/dev/zero of=$dn bs=1M count=1
      wipefs -a $dn
    done
  register: clean_devices
  ignore_errors: true
  with_items:
    - "{{ pools.zfs.zpool }}"
- debug: msg={{ clean_devices }}



#- name: Clean Devices
#  shell: |
#    dd if=/dev/zero of={{ item.source }} bs=1M count=1
#    partprobe {{ item.source }}
#  register: clean_devices
#  ignore_errors: true
#  with_items:
#    - "{{ pools.btrfs.block }}"
#- debug: msg={{ clean_devices }}


- name: Uninstall Relevant Packages for ZFS Storage Pools
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_relevant_pkgs
  ignore_errors: true
  with_items:
    - "zfsutils-linux"
    - "parted"
- debug: msg={{ uninstall_relevant_pkgs }}
# command: cat /proc/partitions

