---
- name: Uninstall CephFS Client Packages
  package: name={{ item }} state=present
  register: uninstall_ceph_clients
  with_items:
    - "ceph-common"
- debug: msg={{ uninstall_ceph_clients }}
  when: print_debug == true


- name: Delete Ceph Configuration in CephFS Clients
  file:
    path:  "/etc/ceph"
    state: absent
  register: delete_ceph_config
- debug: msg={{ delete_ceph_config }}
  when: print_debug == true

