---
pools:
  ceph:
    rbd:
      - { name: "rbd-pool01" }
    fs:
      - { name: "fs-pool01", source: "cephfs-p01-fs01" }
    obj:
  btrfs:
    - { name: "btrfs-pool01", source: "/dev/sdc" }
  dir:
    - { name: "dir-pool01", source: "/mnt/dir-pool01" }
  lvm:
    - { name: "lvm-pool01", source: "/dev/sdb /dev/sdc", vg: "lvm-vg01" }
    thin:
      - { name: "lvm-pool01", source: "/dev/sdb /dev/sdc", size: "5G", vg: "lvm-vg01", vg_pool: "lvm-vg-pool01" }


volumes:
  ceph:
    rbd:
      - { name: "rbd-volume01", size: "1GiB", pool: "rbd-pool01" }
    fs:
      - { name: "fs-volume01", size: "1GiB", pool: "fs-pool01" }
    obj:
  btrfs:
    - { name: "btrfs-volume01", size: "1GiB", pool: "btrfs-pool01" }
  dir:
    - { name: "dir-volume01", size: "1GiB", pool: "dir-pool01" }
  lvm:
    - { name: "lvm-volume01", size: "1GiB", pool: "lvm-pool01" }

