
- hosts: lab
  tasks:
    - name: "{{ power_title }} Virtual Machines"
      become: true
      shell: |
        virsh {{ power_state }} {{ item }}
      loop: "{{ incus.vms.ubt24 }}"
        # - "{{ _incus.vms.rk9 }}"

