# After creating a managed network, you can attach it to an instance as a NIC device.
#
# To do so, use the following command:
$ incus network attach <network_name> <instance_name> [<device_name>] [<interface_name>]

# The device name and the interface name are optional, but we recommend specifying at least the device name.
# If not specified, Incus uses the network name as the device name, which might be confusing and cause problems.
# For example, Incus images perform IP auto-configuration on the eth0 interface, which does not work if the interface is called differently.
#
# For example, to attach the network my-network to the instance my-instance as eth0 device, enter the following command:
$ incus network attach my-network my-instance eth0

# Attach the network as a device
# The incus network attach command is a shortcut for adding a NIC device to an instance. Alternatively, you can add a NIC device based on the network configuration in the usual way:
$ incus config device add <instance_name> <device_name> nic network=<network_name>

# When using this way, you can add further configuration to the command to override the default settings for the network if needed. See NIC device for all available device options.
#
# Attach the network as a device
# The incus network attach command is a shortcut for adding a NIC device to an instance. Alternatively, you can add a NIC device based on the network configuration in the usual way:
$ incus config device add <instance_name> <device_name> nic network=<network_name>

# When using this way, you can add further configuration to the command to override the default settings for the network if needed. See NIC device for all available device options.
