# You can add port specifications to the network forward to forward traffic from specific ports on the listen address to specific ports on the target address.
# This target address must be different from the default target address. It must be within the same subnet as the network that the forward is associated to.
#
# Use the following command to add a port specification:
$ incus network forward port add <network_name> <listen_address> <protocol> <listen_ports> <target_address> [<target_ports>]

# You can specify a single listen port or a set of ports. If you want to forward the traffic to different ports, you have two options:
# Specify a single target port to forward traffic from all listen ports to this target port.
# Specify a set of target ports with the same number of ports as the listen ports to forward traffic from the first listen port to the first target port,
# the second listen port to the second target port, and so on.

