---
#- name: Delete Partition
#  parted:
#    device: "{{ item.source }}"
#    number: "1"
#    state: absent
#  register: delete_partition
#  ignore_errors: true
#  with_items:
#    - "{{ pools.btrfs }}"
#- debug: msg={{ delete_partition }}


#- name: Remove ThinPool LVs
#  lvremove -y {{ item.vg }}/{{ item.thinpool }}


#- name: Remove VGs
#  vgremove {{ item.vg }}


# dmsetup -c info
- name: Clean Devices
  shell: |
    for dn in `echo "{{ item.source }}"`
    do
      dd if=/dev/zero of=$dn bs=1M count=1
    done
  register: clean_devices
  ignore_errors: true
  with_items:
    - "{{ pools.lvm.thin }}"
- debug: msg={{ clean_devices }}


- name: Wipe Filesystem
  shell: |
    for dn in `echo "{{ item.source }}"`
    do
      wipefs -a $dn
    done
  register: wipe_fs
  ignore_errors: true
  with_items:
    - "{{ pools.lvm.thin }}"
- debug: msg={{ wipe_fs }}


#- name: Uninstall Parted
#  package:
#    name: parted
#    state: absent
#  register: uninstall_parted
#  ignore_errors: true
#- debug: msg={{ uninstall_parted }}
# command: cat /proc/partitions

