---
- name: Delete LVM Thin VGs Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.lvm.thin }}"
- debug: msg={{ delete_pools }}

