---
- name: Create Bridge Network
  import_tasks: br/create-network.yml
  tags: enable, create, install
  when: ( br is defined and br == true )


- name: Delete Bridge Network
  import_tasks: br/delete-network.yml
  tags: disable, delete, uninstall
  when: ( br is defined and br == true )


# https://linuxcontainers.org/incus/docs/main/howto/network_ovn_setup/

