---
- name: Unmount Btrfs Directory
  mount:
    path: "{{ item.source }}"
    state: unmounted
  register: unmount_dir
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.dirs }}"
- debug: msg={{ unmount_dir }}


- name: Delete Partition
  parted:
    device: "{{ item.device }}"
    number: "1"
    state: absent
  register: delete_partition
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.dirs }}"
- debug: msg={{ delete_partition }}


- name: Clean Devices
  shell: |
    for dn in `echo "{{ item.device }}"`
    do
      dd if=/dev/zero of=$dn bs=1M count=1
    done
  register: clean_devices
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.dirs }}"
- debug: msg={{ clean_devices }}


- name: Wipe Filesystem
  shell: |
    for dn in `echo "{{ item.device }}"`
    do
      wipefs -a $dn
    done
  register: wipe_fs
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.dirs }}"
- debug: msg={{ wipe_fs }}


- name: Uninstall Parted
  package:
    name: parted
    state: absent
  register: uninstall_parted
  ignore_errors: true
- debug: msg={{ uninstall_parted }}
# command: cat /proc/partitions

