---
- name: Delete Directory for Btrfs Directory Pools
  file:
    path: "{{ item.source }}"
    state: absent
  register: delete_directory
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.dirs }}"
- debug: msg={{ delete_directory }}

