---
- name: Create Linstor File Thin Volumes
  shell: |
    incus storage volume create {{ item.pool }} {{ item.name }}
  register: create_linstor_file_thin_volumes
  with_items:
    - { pool: "linstor-filethin-pool01", name: "linstor-test-thin-vol01" }
  when: inventory_hostname in groups['control']
- debug: msg={{ create_linstor_file_thin_volumes }}
  when: print_debug == true and inventory_hostname in groups['control']

