---
- name: Create Linstor File Thin Pools
  import_tasks: linstor/file/create-pools.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create Linstor File Thin Volumes
  import_tasks: linstor/file/create-volumes.yml
  tags: create, install
  when: inventory_hostname in groups['control']


- name: Delete Linstor File Thin Volumes
  import_tasks: linstor/file/delete-volumes.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete Linstor File Thin Pools
  import_tasks: linstor/file/delete-pools.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']

