---
- name: Delete LVM VG Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.lvm.vg }}"
- debug: msg={{ delete_pools }}

