- name: Delete Physical Network
  shell: |
    incus network delete {{ item.name }}
  register: delete_physical_network
  with_items:
    - "{{ _phy }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ delete_physical_network }}
  when: print_debug == true and inventory_hostname in groups['control']

