---
- name: Delete ZFS Volumes
  shell: |
    incus storage volume delete {{ item.pool }} {{ item.name }}
  register: delete_volumes
  ignore_errors: true
  with_items:
    - "{{ volumes.zfs.block }}"
- debug: msg={{ delete_volumes }}

