---
- name: Install Relevant Packages for ZFS Storage Pools
  package:
    name: "{{ item }}"
    state: present
  register: install_relevant_pkgs
  ignore_errors: true
  with_items:
    - "parted"
    - "zfsutils-linux"
- debug: msg={{ install_relevant_pkgs }}
# command: cat /proc/partitions


#- name: Create ZFS ZPool
#  shell: |
#    zpool create {{ item.zpool }} {{ item.source }}
#  register: create_zpool
#  ignore_errors: true
#  with_items:
#    - "{{ pools.zfs.block }}"
#- debug: msg={{ create_zpool }}
# dd if=/dev/zero of="{{ item.source }}1" seek=$(( $(blockdev --getsz "{{ item.source }}1") - ( ( 256 * 1024 * 2) / $(blockdev --getpbsz "{{ item.source}}1") ) ))


- name: Clean Devices
  shell: |
    dd if=/dev/zero of={{ item.source }} bs=1M count=100
  register: clean_devices
  ignore_errors: true
  with_items:
    - "{{ pools.zfs.block }}"
- debug: msg={{ clean_devices }}
# dd if=/dev/zero of="{{ item.source }}1" seek=$(( $(blockdev --getsz "{{ item.source }}1") - ( ( 256 * 1024 * 2) / $(blockdev --getpbsz "{{ item.source}}1") ) ))


- name: Wipe Filesystem
  shell: |
    wipefs -a {{ item.source }}
  register: wipe_fs
  ignore_errors: true
  with_items:
    - "{{ pools.zfs.block }}"
- debug: msg={{ wipe_fs }}


#- name: Delete Partition
#  parted:
#    device: "{{ item.source }}"
#    number: "1"
#    state: absent
#  register: delete_partition
#  ignore_errors: true
#  with_items:
#    - "{{ pools.zfs.block }}"
#- debug: msg={{ delete_partition }}


#- name: Uninstall Parted
#  package:
#    name: parted
#    state: absent
#  register: uninstall_parted
#  ignore_errors: true
#- debug: msg={{ uninstall_parted }}
# command: cat /proc/partitions

