---
- name: Prepare ZFS ZPool Slice Pools with Cluster Mode
  shell: |
    incus storage create {{ item.name }} zfs source={{ item.zpool }}/{{ item.slice }} --target={{ inventory_hostname }}
  register: prepare_cluster_pools
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ pools.zfs.slice }}"
- debug: msg={{ prepare_cluster_pools }}
  # Failed
  # incus storage create {{ item.name }} zfs source={{ item.zpool }}/{{ item.slice }} volume.zfs.block_mode=yes --target={{ inventory_hostname }}


- name: Create ZFS ZPool Slice Pools
  shell: |
    incus storage create {{ item.name }} zfs
  register: create_pools
  with_items:
    - "{{ pools.zfs.slice }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_pools }}
  when: print_debug == true and inventory_hostname in groups['control']

