---
- name: Delete ZFS Zpool Slice Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.zfs.slice }}"
- debug: msg={{ delete_pools }}

