---
- name: Unstall Incus UI Software Packages
  package: name={{ item }} state=absent
  with_items:
    - incus-ui-canonical
    - incus-client


- name: Update Caches for APT Packages
  apt:
    update_cache: yes
    cache_valid_time: 86400   # One day
  register: update_apt_cache
  until: update_apt_cache is succeeded
  retries: 20
  delay: 20
  # upgrade: yes

