# If you have image files that use the required Image format, you can import them into your image store.
# There are several ways of obtaining such image files:
# Exporting an existing image (see Export an image to a file)
# Building your own image using distrobuilder (see Build an image)
# Downloading image files from a remote image server (note that it is usually easier to use the remote image directly instead of downloading it to a file and importing it)
#
# Import from the local file system
# To import an image from the local file system, use the incus image import command.
# This command supports both unified images (compressed file or directory) and split images (two files).
# To import a unified image from one file or directory, enter the following command:
$ incus image import <image_file_or_directory_path> [<target_remote>:]

# To import a split image, enter the following command:
$ incus image import <metadata_tarball_path> <rootfs_tarball_path> [<target_remote>:]

# In both cases, you can assign an alias with the --alias flag. See incus image import --help for all available flags.
#
# Import from a file on a remote web server
# You can import image files from a remote web server by URL. This method is an alternative to running an Incus server for the sole purpose of distributing an image to users. It only requires a basic web server with support for custom headers (see Custom HTTP headers).
#
# The image files must be provided as unified images (see Unified tarball).

# To import an image file from a remote web server, enter the following command:
$ incus image import <URL>

# You can assign an alias to the local image with the --alias flag.
#
# Custom HTTP headers
# Incus requires the following custom HTTP headers to be set by the web server:
#
# Incus-Image-Hash
# The SHA256 of the image that is being downloaded.
# 
# Incus-Image-URL
# The URL from which to download the image.
#
# Incus sets the following headers when querying the server:
# 
# Incus-Server-Architectures
# A comma-separated list of architectures that the client supports.
#
# Incus-Server-Version
# The version of Incus in use.


