---
- name: Install Parted
  package:
    name: parted
    state: present
  register: install_parted
  ignore_errors: true
- debug: msg={{ install_parted }}
# command: cat /proc/partitions


#- name: Delete Partition
#  parted:
#    device: "{{ item.source }}"
#    number: "1"
#    state: absent
#  register: delete_partition
#  ignore_errors: true
#  with_items:
#    - "{{ pools.btrfs.block }}"
#- debug: msg={{ delete_partition }}


- name: Clean Devices
  shell: |
    dd if=/dev/zero of={{ item.source }} bs=1M count=1
  register: clean_devices
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.block }}"
- debug: msg={{ clean_devices }}


- name: Run Partprobe
  shell: |
    partprobe {{ item.source }}
  register: run_partprobe
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.block }}"
- debug: msg={{ run_partprobe }}


#- name: Uninstall Parted
#  package:
#    name: parted
#    state: absent
#  register: uninstall_parted
#  ignore_errors: true
#- debug: msg={{ uninstall_parted }}
# command: cat /proc/partitions

