---
- name: Prepare Btrfs Block Pools with Cluster Mode
  shell: |
    incus storage create {{ item.name }} btrfs source={{ item.source }} --target={{ inventory_hostname }}
  register: prepare_cluster_btrfs_pools
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ pools.btrfs.block }}"
- debug: msg={{ prepare_cluster_btrfs_pools }}


- name: Create Btrfs Block Pools
  shell: |
    incus storage create {{ item.name }} btrfs
  register: create_pools
  with_items:
    - "{{ pools.btrfs.block }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_pools }}
  when: print_debug == true and inventory_hostname in groups['control']

