---
- name: Delete Btrfs Block Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.btrfs.block }}"
- debug: msg={{ delete_pools }}

