---
- name: Install Parted
  package:
    name: parted
    state: present
  register: install_parted
- debug: msg={{ install_parted }}


#- name: "Add new partition"
#  parted:
#    device: "{{ item.source }}"
#    number: 1
#    flags: [ lvm ]
#    state: present
#  register: add_partition
#  with_items:
#    - "{{ pools.btrfs.block }}"
#- debug: msg={{ add_partition }}
#
#
#- name: Format the Partition
#  filesystem:
#    fstype: btrfs
#    dev: "{{ item.source }}1"
#  register: format_partition
#  with_items:
#    - "{{ pools.btrfs.block }}"
#- debug: msg={{ format_partition }}

