---
- name: Create ZFS Local Volumes
  shell: |
    incus storage volume create {{ item.pool }} {{ item.name }}
  register: create_volumes
  with_items:
    - "{{ volumes.zfs.local }}"
- debug: msg={{ create_volumes }}
  when: print_debug == true

