---
- name: Prepare ZFS Local Storage Pools
  import_tasks: zfs/local/prepare-zfs.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create ZFS Local Storage Pools
  import_tasks: zfs/local/create-pools.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create ZFS Local Storage Volumes
  import_tasks: zfs/local/create-volumes.yml
  tags: create, install
  when: inventory_hostname in groups['control']


- name: Delete ZFS Local Storage Volumes
  import_tasks: zfs/local/delete-volumes.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete ZFS Local Storage Pools
  import_tasks: zfs/local/delete-pools.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete ZFS Storage Devices
  import_tasks: zfs/local/clean-devices.yml
  tags: clean, delete, uninstall
  when: inventory_hostname in groups['workers']

