---
- name: Install Relevant OVN Packages
  package:
    name: "{{ item }}"
    state: present
  register: install_relevant_pkgs
  ignore_errors: true
  with_items:
    - "ovn-central"
    - "ovn-host"
- debug: msg={{ install_relevant_pkgs }}
  when: print_debug == true


- name: Enable OVN Service
  systemd:
    name: "{{ item.svc }}"
    state: "{{ item.action }}"
    enabled: true
    daemon_reload: true
  register: enable_ovn
  until: enable_ovn is succeeded
  retries: 3
  delay: 10
  with_items:
    - { svc: "ovn-central", action: "stopped" }
    - { svc: "ovn-host", action: "stopped" }
- debug: msg={{ enable_ovn }}
  when: print_debug == true

