---
- name: Delete OVN Network
  shell: |
    incus network delete {{ item.name }}
  register: delete_network
  ignore_errors: true
  with_items:
    - "{{ _ovn }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ delete_network }}
  when: print_debug == true and inventory_hostname in groups['control']

