---
- name: Disable OVN Service
  systemd:
    name: "{{ item.svc }}"
    state: "{{ item.state }}"
    enabled: "{{ item.action }}"
    daemon_reload: true
  register: disable_ovn
  until: disable_ovn is succeeded
  retries: 3
  delay: 10
  with_items:
    - { svc: "ovn-host", state: "stopped", action: "false" }
    - { svc: "ovn-central", state: "stopped", action: "false" }
- debug: msg={{ disable_ovn }}
  when: print_debug == true


- name: Uninstall Relevant OVN Packages
  package:
    name: "{{ item.pkg }}"
    state: "{{ item.state }}"
  register: uninstall_relevant_pkgs
  ignore_errors: true
  with_items:
    - { pkg: "ovn-host", state: "absent" }
    - { pkg: "ovn-central", state: "absent" }
- debug: msg={{ uninstall_relevant_pkgs }}
  when: print_debug == true

