---
- name: Stop OVN Service to Apply Changes
  systemd:
    name: "{{ item.svc }}"
    state: "{{ item.action }}"
    enabled: false
    daemon_reload: true
  register: stop_ovn
  ignore_errors: true
  until: stop_ovn is succeeded
  retries: 3
  delay: 10
  with_items:
    - { svc: "ovn-central", action: "stopped" }
    - { svc: "ovn-host", action: "stopped" }
- debug: msg={{ stop_ovn }}
  when: print_debug == true


- name: Uninstall Relevant OVN Packages
  package:
    name: "{{ item }}"
    state: absent
  register: uninstall_relevant_pkgs
  ignore_errors: true
  with_items:
    - "ovn-central"
    - "ovn-host"
- debug: msg={{ uninstall_relevant_pkgs }}


#- name: Create ZFS ZPool
#  shell: |
#    zpool create {{ item.zpool }} {{ item.source }}
#  register: create_zfs_zpool
#  ignore_errors: true
#  with_items:
#    - "{{ pools.zfs.zpool }}"
#- debug: msg={{ create_zfs_zpool }}
# dd if=/dev/zero of="{{ item.source }}1" seek=$(( $(blockdev --getsz "{{ item.source }}1") - ( ( 256 * 1024 * 2) / $(blockdev --getpbsz "{{ item.source}}1") ) ))

