---
- name: Enable OVN Service
  import_tasks: ovn/cluster/01-enable-ovn-service.yml
  tags: enable, install


- name: Config OVN Service
  import_tasks: ovn/cluster/02-config-ovn-service.yml
  tags: config, install


- name: Start OVN Service
  import_tasks: ovn/cluster/03-start-ovn-services.yml
  tags: start, install


- name: Configure Open Vsiwtch
  import_tasks: ovn/cluster/04-config-open-vswitch.yml
  tags: config, install


- name: Create OVN Network
  import_tasks: ovn/cluster/05-create-ovn-network.yml
  tags: create


- name: Remove OVN Service
  import_tasks: ovn/cluster/06-remove-ovn-service.yml
  tags: disable, delete, uninstall


- name: Disable OVN Service
  import_tasks: ovn/cluster/07-disable-ovn-service.yml
  tags: disable, delete, uninstall


# https://linuxcontainers.org/incus/docs/main/howto/network_ovn_setup/

