---
- name: Enable Linstor Clients
  import_tasks: linstor/enable-linstor-clients.yml
  tags: enable
  when: ( client is defined and client == true )


- name: Import Linstor Storage Pools
  import_tasks: linstor/pool/main.yml
  when: ( pool is defined and pool == true )


- name: Disable Linstor Clients
  import_tasks: linstor/disable-linstor-clients.yml
  tags: disable
  when: ( client is defined and client == true )

