---
- name: Waiting for Server to Come Back After Reboot
  local_action: wait_for host={{ hostvars[inventory_hostname].ansible_ssh_host }} port=22 state=started delay=10 timeout=300 connect_timeout=300 search_regex=OpenSSH
  become: no

- name: Restart System
  shell: ( /bin/sleep 5 ; /sbin/shutdown -r now "Ansible updates triggered" ) &
  async: 30
  poll: 0


- name: Start Incus
  service: name=incus state=started enabled=yes


- name: Stop Incus
  service: name=incus state=stopped enabled=no


- name: Restart Incus
  service: name=incus state=restarted enabled=yes


- name: Sync Incus DB
  shell: incus admin sql global .sync

