# Complete the following steps to set up a LXD cluster that uses an OVN network.
# Just like LXD, the distributed database for OVN must be run on a cluster that consists of an odd number of members. The following instructions use the minimum of three servers, which run both the distributed database for OVN and the OVN controller. In addition, you can add any number of servers to the LXD cluster that run only the OVN controller. See the linked YouTube video for the complete tutorial using four machines.
#
# Complete the following steps on the three machines that you want to run the distributed database for OVN:


- name: Install the OVN tools
  shell: |
    apt install ovn-central ovn-host


- name: Mark the OVN services as enabled to ensure that they are started when the machine boots
  shell: |
    systemctl enable ovn-central
    systemctl enable ovn-host


- name: Stop OVN for now
  shell: |
    systemctl stop ovn-central


- name: Note down the IP address of the machine
  shell: |
    ip -4 a


# Open /etc/default/ovn-central for editing.
#
# Paste in one of the following configurations (replace <server_1>, <server_2> and <server_3> with the IP addresses of the respective machines,
# and <local> with the IP address of the machine that you are on).


- name: For the first machine:
  shell: |
    OVN_CTL_OPTS=" \
    --db-nb-addr=<local> \
    --db-nb-create-insecure-remote=yes \
    --db-sb-addr=<local> \
    --db-sb-create-insecure-remote=yes \
    --db-nb-cluster-local-addr=<local> \
    --db-sb-cluster-local-addr=<local> \
    --ovn-northd-nb-db=tcp:<server_1>:6641,tcp:<server_2>:6641,tcp:<server_3>:6641 \
    --ovn-northd-sb-db=tcp:<server_1>:6642,tcp:<server_2>:6642,tcp:<server_3>:6642"


- name: For the second and third machine:
  shell: |
    OVN_CTL_OPTS=" \
    --db-nb-addr=<local> \
    --db-nb-cluster-remote-addr=<server_1> \
    --db-nb-create-insecure-remote=yes \
    --db-sb-addr=<local> \
    --db-sb-cluster-remote-addr=<server_1> \
    --db-sb-create-insecure-remote=yes \
    --db-nb-cluster-local-addr=<local> \
    --db-sb-cluster-local-addr=<local> \
    --ovn-northd-nb-db=tcp:<server_1>:6641,tcp:<server_2>:6641,tcp:<server_3>:6641 \
    --ovn-northd-sb-db=tcp:<server_1>:6642,tcp:<server_2>:6642,tcp:<server_3>:6642"


- name: Start OVN:
  shell: |
    systemctl start ovn-central


- name: On the remaining machines, install only ovn-host and make sure it is enabled:
  shell: |
    apt install ovn-host
    systemctl enable ovn-host


- name: On all machines, configure Open vSwitch (replace the variables as described above)
  shell: |
    ovs-vsctl set open_vswitch . \
    external_ids:ovn-remote=tcp:<server_1>:6642,tcp:<server_2>:6642,tcp:<server_3>:6642 \
    external_ids:ovn-encap-type=geneve \
    external_ids:ovn-encap-ip=<local>


# Create a LXD cluster by running lxd init on all machines. On the first machine, create the cluster.
# Then join the other machines with tokens by running lxc cluster add <machine_name> on the first machine
# and specifying the token when initializing LXD on the other machine.


- name: On the first machine, create and configure the uplink network
  shell: |
    incus network create UPLINK --type=physical parent=<uplink_interface> --target=<machine_name_1> \
    incus network create UPLINK --type=physical parent=<uplink_interface> --target=<machine_name_2> \
    incus network create UPLINK --type=physical parent=<uplink_interface> --target=<machine_name_3> \
    incus network create UPLINK --type=physical parent=<uplink_interface> --target=<machine_name_4> \
    incus network create UPLINK --type=physical \
    ipv4.ovn.ranges=<IP_range> \
    ipv6.ovn.ranges=<IP_range> \
    ipv4.gateway=<gateway> \
    ipv6.gateway=<gateway> \
    dns.nameservers=<name_server>


#- name: To determine the required values
#  Uplink interface
#  A high availability OVN cluster requires a shared layer 2 network, so that the active OVN chassis can move between cluster members (which effectively allows the OVN router’s external IP to be reachable from a different host).
#
#  Therefore, you must specify either an unmanaged bridge interface or an unused physical interface as the parent for the physical network that is used for OVN uplink. The instructions assume that you are using a manually created unmanaged bridge. See How to configure network bridges for instructions on how to set up this bridge.


# [ Gateway ]
# Run ip -4 route show default and ip -6 route show default
#
# [ Name server ]
# Run resolvectl
#
# [ IP ranges ]
# Use suitable IP ranges based on the assigned IPs


# Still on the first machine, configure LXD to be able to communicate with the OVN DB cluster
# To do so, find the value for ovn-northd-nb-db in /etc/default/ovn-central and
# provide it to LXD with the following command


- name: Provide it to LXD with the following command:
  shell: |
    incus config set network.ovn.northbound_connection <ovn-northd-nb-db>


# [ Note ]
# If you are using a MicroOVN deployment, pass the value of the MicroOVN node IP address you want to target. Prefix the IP address with ssl:, and suffix it with the :6641 port number that corresponds to the OVN central service within MicroOVN.


- name: Finally, create the actual OVN network (on the first machine)
  shell: |
    incus network create my-ovn --type=ovn


- name: To test the OVN network, create some instances and check the network connectivity
  shell: |
    incus launch ubuntu:24.04 c1 --network my-ovn
    incus launch ubuntu:24.04 c2 --network my-ovn
    incus launch ubuntu:24.04 c3 --network my-ovn
    incus launch ubuntu:24.04 c4 --network my-ovn
    incus list
    incus exec c4 -- bash
    ping <IP of c1>
    ping <nameserver>
    ping6 -n www.example.com


