---
- name: Delete Linstor Storage Volumes
  shell: |
    incus storage volume delete {{ item.pool }} {{ item.name }}
  register: delete_linstor_storage_volumes
  ignore_errors: true
  with_items: "{{ volumes.linstor.lvm }}"
- debug: msg={{ delete_linstor_storage_volumes }}

