---
- name: Create Cluster LVM Volumes
  shell: |
    incus storage volume create {{ item.pool }} {{ item.name }}
  register: create_volumes
  with_items:
    - "{{ volumes.lvm.cluster }}"
- debug: msg={{ create_volumes }}
  when: print_debug == true

