
https://www.microfocus.com/documentation/open-enterprise-server/2023/clus_admin_lx/bxvario.html

https://www.server-world.info/en/note?os=Ubuntu_22.04&p=pacemaker&f=3#google_vignette

https://shape.host/resources/lvm-configuration-for-high-availability-clusters

