---
- name: Prepare LVM Cluster Environment
  import_tasks: lvm/cluster/prepare-lvm-cluster-env.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create Volume Cluster Volume Groups
  import_tasks: lvm/cluster/create-vg.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create LVM Cluster VGs Pools
  import_tasks: lvm/cluster/create-pools.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create LVM Cluster VGs Volumes
  import_tasks: lvm/cluster/create-volumes.yml
  tags: create, install
  when: inventory_hostname in groups['control']


- name: Delete LVM Cluster VGs Volumes
  import_tasks: lvm/cluster/delete-volumes.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete LVM Cluster VGs Pools
  import_tasks: lvm/cluster/delete-pools.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Destroy LVM Cluster Environment
  import_tasks: lvm/cluster/destroy-lvm-cluster-env.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['workers']

