---
- name: Install Relevant Packages for Clustered-LVM Pools
  package:
    name: "{{ item }}"
    state: present
  register: install_relevant_pkgs
  ignore_errors: true
  with_items:
    - "lvm2-lockd"
    - "sanlock"
- debug: msg={{ install_relevant_pkgs }}


#- name: Enable LVM Cluster Lock
#  lineinfile:
#    dest: "{{ item.dest }}"
#    regexp: "{{ item.regexp }}"
#    line: "{{ item.line }}"
#    state: "{{ item.state }}"
#  register: enable_lvm_cluster_lock
#  with_items:
#    - { regexp: "^        # use_lvmlockd = 0",   line: "        use_lvmlockd = 1",          dest: "/etc/lvm/lvm.conf",       state: present }
#    - { regexp: "^        # host_id = 0",        line: "        host_id = {{ host_id }}",   dest: "/etc/lvm/lvmlocal.conf",  state: present }
#- debug: msg={{ enable_lvm_cluster_lock }}
#  when: print_debug == true


- name: Enable LVM Cluster Lock
  replace:
    path: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  register: enable_lvm_cluster_lock
  with_items:
    - { regexp: "# use_lvmlockd = 0",   line: "use_lvmlockd = 1",          dest: "/etc/lvm/lvm.conf",       state: present }
    - { regexp: "# host_id = 0",        line: "host_id = {{ host_id }}",   dest: "/etc/lvm/lvmlocal.conf",  state: present }
- debug: msg={{ enable_lvm_cluster_lock }}
  when: print_debug == true



- name: Start Cluster LVM
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  register: start_cluster_lvm
  ignore_errors: true
  until: start_cluster_lvm is succeeded
  retries: 3
  delay: 10
  with_items:
    - sanlock
    - lvmlockd
- debug: msg={{ start_cluster_lvm }}
  when: print_debug == true


#- name: Delete Partition
#  parted:
#    device: "{{ item.source }}"
#    number: "1"
#    state: absent
#  register: delete_partition
#  ignore_errors: true
#  with_items:
#    - "{{ pools.zfs }}"
#- debug: msg={{ delete_partition }}


#- name: Uninstall Parted
#  package:
#    name: parted
#    state: absent
#  register: uninstall_parted
#  ignore_errors: true
#- debug: msg={{ uninstall_parted }}
# command: cat /proc/partitions

