- name: Stop Cluster LVM
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
  register: stop_cluster_lvm
  ignore_errors: true
  until: stop_cluster_lvm is succeeded
  retries: 3
  delay: 10
  with_items:
    - lvmlockd
    - sanlock
- debug: msg={{ stop_cluster_lvm }}
  when: print_debug == true
