---
- name: Prepare ZFS LoopBack Storage Pools
  import_tasks: zfs/loopback/prepare-zfs.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create ZFS LoopBack Storage Pools
  import_tasks: zfs/loopback/create-pools.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create ZFS LoopBack Storage Volumes
  import_tasks: zfs/loopback/create-volumes.yml
  tags: create, install
  when: inventory_hostname in groups['control']


- name: Delete ZFS LoopBack Storage Volumes
  import_tasks: zfs/loopback/delete-volumes.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete ZFS LoopBack Storage Pools
  import_tasks: zfs/loopback/delete-pools.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete ZFS Storage Devices
  import_tasks: zfs/loopback/clean-devices.yml
  tags: clean, delete, uninstall
  when: inventory_hostname in groups['workers']

