---
- name: Delete Ceph RadosGW Volumes
  shell: |
    incus storage volume delete {{ item.pool }} {{ item.name }}
  register: delete_volumes
  ignore_errors: true
  with_items:
    - "{{ volumes.ceph.rgw }}"
- debug: msg={{ delete_volumes }}

