---
- name: Delete Ceph RadosGW Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.ceph.rgw }}"
- debug: msg={{ delete_pools }}

