---
- name: Create RadosGW Pools
  import_tasks: ceph/rgw/create-pools.yml
  tags: create, install
  when: inventory_hostname in groups['workers']


- name: Create Ceph RadosGW Volumes
  import_tasks: ceph/rgw/create-volumes.yml
  tags: create, install
  when: inventory_hostname in groups['control']


- name: Delete Ceph RadosGW Volumes
  import_tasks: ceph/rgw/delete-volumes.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']


- name: Delete Ceph RaodsGW Pools
  import_tasks: ceph/rgw/delete-pools.yml
  tags: delete, uninstall
  when: inventory_hostname in groups['control']

