# See the Storage drivers documentation for the available configuration options for each storage driver.
#
# Use the following command to set configuration options for a storage volume:
$ incus storage volume set <pool_name> [<volume_type>/]<volume_name> <key> <value>


# The default storage volume type is custom, so you can leave out the <volume_type>/ when configuring a custom storage volume.
# For example, to set the size of your custom storage volume my-volume to 1 GiB, use the following command:
$ incus storage volume set my-pool my-volume size=1GiB

# To set the snapshot expiry time for your virtual machine my-vm to one month, use the following command:
$ incus storage volume set my-pool virtual-machine/my-vm snapshots.expiry 1M

# You can also edit the storage volume configuration by using the following command:
# incus storage volume edit <pool_name> [<volume_type>/]<volume_name>

# Configure default values for storage volumes
# You can define default volume configurations for a storage pool.
# To do so, set a storage pool configuration with a volume prefix, thus volume.<VOLUME_CONFIGURATION>=<VALUE>.

# This value is then used for all new storage volumes in the pool, unless it is set explicitly for a volume or an instance. In general, the defaults set on a storage pool level (before the volume was created) can be overridden through the volume configuration, and the volume configuration can be overridden through the instance configuration (for storage volumes of type container or virtual-machine).
# For example, to set a default volume size for a storage pool, use the following command:
$ incus storage set [<remote>:]<pool_name> volume.size <value>


