---
- name: Create Linstor Storage Volumes
  shell: |
    incus storage volume create {{ item.pool }} {{ item.name }}
  register: create_linstor_storage_volumes
  with_items: "{{ volumes.linstor.filethin }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_linstor_storage_volumes }}
  when: print_debug == true and inventory_hostname in groups['control']

