---
- name: Delete Directory Local Pools
  shell: |
    incus storage delete {{ item.name }}
  register: delete_pools
  ignore_errors: true
  with_items:
    - "{{ pools.dir.local }}"
- debug: msg={{ delete_pools }}

