# Resize a storage bucket
# By default, storage buckets do not have a quota applied.

- name: To set or change a quota for a storage bucket, set its size configuration
  shell: |
    incus storage bucket set <pool_name> <bucket_name> size <new_size>

# [ Important ]
# Growing a storage bucket usually works (if the storage pool has sufficient storage).
# You cannot shrink a storage bucket below its current used size.


