---
- name: Delete Ceph Filesystem Volumes
  shell: |
    incus storage volume delete {{ item.pool }} {{ item.name }}
  register: delete_ceph_fs_volumes
  ignore_errors: true
  with_items:
    - "{{ volumes.ceph.fs }}"
- debug: msg={{ delete_ceph_fs_volumes }}

