---
- name: Create Ceph RBD Volumes
  shell: |
    incus storage volume create {{ item.pool }} {{ item.name }}
  register: create_ceph_rbd_volumes
  with_items:
    - "{{ volumes.ceph.rbd }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_ceph_rbd_volumes }}
  when: print_debug == true and inventory_hostname in groups['control']

