---
- name: Create Directory for Directory Pools
  file:
    path: "{{ item.source }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  register: create_directory
  with_items:
    - "{{ pools.dir.dirs }}"
- debug: msg={{ create_directory }}


- name: Prepare Directory Pools with Cluster Mode
  shell: |
    incus storage create {{ item.name }} dir source={{ item.source }} --target={{ inventory_hostname }}
  register: prepare_cluster_pools
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  with_items:
    - "{{ pools.dir.dirs }}"
- debug: msg={{ prepare_cluster_pools }}


- name: Create Directory Pools
  shell: |
    incus storage create {{ item.name }} dir
  register: create_pools
  with_items:
    - "{{ pools.dir.dirs }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ create_pools }}
  when: print_debug == true and inventory_hostname in groups['control']

