---
- name: Check if Incus CA Key Exists
  stat: path=/root/incus-ui.crt
  register: incus_ca_key
  when: inventory_hostname in groups['control']
- debug: msg={{ incus_ca_key }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Copy Incus CA Key File Downloaded from Directory til Success
  become_user: jomoon
  shell: |
    sshpass -p "changeme" scp -o StrictHostKeyChecking=no {{ _incus.local_download_dir }}/incus-ui.crt root@192.168.2.183:/root/
  register: scp_ca_key
  until: scp_ca_key is succeeded
  retries: 100
  delay: 10
  delegate_to: localhost
  failed_when: scp_ca_key.rc != 0
  when: inventory_hostname in groups['control']
- debug: msg={{ scp_ca_key }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Register Incus CA Key File Downloaded
  shell: |
    incus config trust add-certificate /root/incus-ui.crt
  register: scp_ca_key
  when: inventory_hostname in groups['control']
- debug: msg={{ scp_ca_key }}
  when: print_debug == true and inventory_hostname in groups['control']

