---
- name: Get Token for Join Cluster
  shell: |
    incus cluster add 192.168.2.183
  async: 360
  poll: 5
  register: get_token
  when: inventory_hostname in groups['control']
- debug: msg={{ get_token }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Set Fact for Token CA Certificate
  set_fact:
    join_token: "{{ get_token.stdout_lines[-1:] }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['workers'] }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ join_token }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Copy Zabbly Repository Config
  template:
    src: preseed.yaml.j2
    dest: /root/preseed.yaml
    owner: root
    group: root
    mode: 644
    force: yes
  register: copy_zabbly_repo_config
- debug: msg={{ copy_zabbly_repo_config }}
  when: print_debug == true
# cat preseed.yaml | incus admin init --preseed



# In node01
# incus config set core.https_address 192.168.0.181:8443
# incus cluster enable 192.168.0.182 ubt24-node02
# Clustering enabled



# incus cluster enable 192.168.2.181 ubt24-node01
# incus cluster add 192.168.2.182

