---
- name: Check OS ( Incus )
  fail: msg="Not a Debian or Ubuntu based system!"
  when: inventory_hostname in groups['workers'] and ( ansible_os_family != 'Ubuntu' or ansible_os_family != 'Debian' )


- name: Set Facts For Network and Packages Informations and other Versions
  import_tasks: set-facts.yml
  tags:
    - install
    - uninstall
    - prepare
    - cleanup
  when: inventory_hostname in groups['workers']


- name: Prepare Incus Environment as Setup Repository and Install Packages
  import_tasks: install-incus.yml
  tags: install
  when: ( incus is defined and incus == true ) and inventory_hostname in groups['workers']


- name: Install Incus Web UI
  import_tasks: install-incus-ui.yml
  tags: install
  when: ( ui is defined and ui == true ) and inventory_hostname in groups['control']


- name: Add Incus Cluster
  import_tasks: enable-cluster.yml
  tags: install
  when: ( add is defined and add == true ) and inventory_hostname in groups['workers']


- name: Uninstall Incus Web UI
  import_tasks: uninstall-incus-ui.yml
  tags: uninstall
  when: ( ui is defined and ui == true ) and inventory_hostname in groups['control']


- name: Prepare Incus Environment as Uninstall Packages and Removing Repository
  import_tasks: uninstall-incus.yml
  tags: uninstall
  when: ( incus is defined and incus == true ) and inventory_hostname in groups['workers']




#- name: Disable SELinux and Stop Firewalld
#  import_tasks: disable-selinux.yml
#  tags:
#    - install


#- name: Enable SELinux and Stop Firewalld
#  import_tasks: disable-selinux.yml
#  tags:
#    - uninstall

