---
- name: Get Network Interface Name Filted by Prefix of IP Addresses Provided
  set_fact:
    netdev0: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _incus.net.ipaddr0 ) | map(attribute='device') | first }}"
    netdev2: "{{ ansible_interfaces | map('regex_replace', '^', 'ansible_') | map('extract', vars) | selectattr('ipv4', 'defined') | selectattr('ipv4.address', 'match', _incus.net.ipaddr2 ) | map(attribute='device') | first }}"


- name: Get IP Address Filtered by Network Device Name Provided
  set_fact:
    ipaddr0: "{{ hostvars[inventory_hostname]['ansible_'~netdev0].ipv4.address }}"
    ipaddr2: "{{ hostvars[inventory_hostname]['ansible_'~netdev2].ipv4.address }}"


- name: Set Default Network Device and Address
  set_fact:
    _netdev: "{{ 'ansible_'~ netdev2 }}"
    _ipaddr: "{{ ipaddr2 }}"
    _netdev0: "{{ 'ansible_'~ netdev0 }}"
    _netdev2: "{{ 'ansible_'~ netdev2 }}"


- name: Get Netmask From Provided Network Device Names
  set_fact:
    netmask0: "{{ ( hostvars[inventory_hostname][_netdev0]['ipv4']['address'] + '/' + hostvars[inventory_hostname][_netdev0]['ipv4']['netmask'] ) | ansible.utils.ipaddr('prefix') }}"
    netmask2: "{{ ( hostvars[inventory_hostname][_netdev2]['ipv4']['address'] + '/' + hostvars[inventory_hostname][_netdev2]['ipv4']['netmask'] ) | ansible.utils.ipaddr('prefix') }}"


#- name: Define Facts for All Worker's Hostname
#  set_fact:
#    all_ext1_hostnames: "{{ groups['all'] | map('extract', hostvars, ['ansible_hostname']) | join(' ') }}"
#- debug: msg={{ all_ext1_hostnames }}
#- name: Define Fact for All Worker's First IP Address
#  set_fact:
#    all_net0_ipaddrs: "{{ groups['all'] | map('extract', hostvars, ['ansible_'~netdev0, 'ipv4', 'address']) | join(',') }}"
#- debug: msg={{ all_net0_ipaddrs }}


# - debug: msg="{{ ansible_distribution }}"
# - debug: msg="{{ ansible_distribution_version}}"
# - debug: msg="{{ ansible_distribution_major_version }}"
# - debug: msg="{{ ansible_architecture }}"


- name: Get VERSION CODENAME
  shell: . /etc/os-release && echo ${VERSION_CODENAME}
  register: get_version_codename
- debug: msg="{{ get_version_codename }}"


- name: Get Architecture
  shell: dpkg --print-architecture
  register: get_architecture
- debug: msg="{{ get_architecture }}"


- name: Set Version CodeName and Architecture
  set_fact:
    _version_codename: "{{ get_version_codename.stdout }}"
    _architecture: "{{ get_architecture.stdout }}"

